- name: web server installation
  hosts: all
  become: yes
  gather_facts: true
  tasks:
    - name: Amazon > httpd
      yum:
        name: httpd
        state: present
      when: ansible_distribution == 'Amazon'

    - name: Amazon > index.html
      get_url: url=https://www.daum.net dest=/var/www/html/index.html
      when: ansible_distribution == 'Amazon'

    - name: Amazon > start httpd
      service: name=httpd state=started
      when: ansible_distribution == 'Amazon'

    - name: Ubuntu > nginx
      apt:
        name: nginx
        state: present
      when: ansible_distribution == 'Ubuntu'

    - name: Ubuntu > index.html
      get_url: url=https://www.daum.net dest=/var/www/html/index.html
      when: ansible_distribution == 'Ubuntu'

    - name: Ubuntu > start nginx
      service: name=nginx state=started
      when: ansible_distribution == 'Ubuntu'
